app:
  bucket: ""
  dbHost: ""
  dbName: ""
  dbUser: ""
  dbPassword: ""
  runtimeVar: ""
  runtimeVarWait: ""
  cloudSqlRegion: ""
  runtimeConfigName: ""


deploy:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
    paths: []
    hosts:
      - chart-example.local
    tls: []